[0m22:35:32.925221 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021EB449B0D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021EB3D6B950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021EB3D6B850>]}


============================== 22:35:32.932223 | 210b06c6-cb1c-4ee0-b640-62bdfcbed1a9 ==============================
[0m22:35:32.932223 [info ] [MainThread]: Running with dbt=1.7.3
[0m22:35:32.933221 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:35:59.302985 [debug] [MainThread]: Starter project path: C:\Users\marco\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m22:35:59.449200 [info ] [MainThread]: 
Your new dbt project "school" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:35:59.450199 [info ] [MainThread]: Setting up your profile.
[0m22:46:08.692433 [info ] [MainThread]: Profile school written to C:\Users\marco\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:46:08.696982 [debug] [MainThread]: Command `dbt init` succeeded at 22:46:08.696982 after 635.85 seconds
[0m22:46:08.700290 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021EACD31090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021EACFA4450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021EB44AC050>]}
[0m22:46:08.702818 [debug] [MainThread]: Flushing usage events
[0m23:11:35.582988 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002765953E090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027659017B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027659082110>]}


============================== 23:11:35.587984 | e2cf6dbb-59d7-454e-80a4-a6f401260b2b ==============================
[0m23:11:35.587984 [info ] [MainThread]: Running with dbt=1.7.3
[0m23:11:35.589354 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:11:35.590356 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\OneDrive\Documentos\triade\dbt_study_case\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:11:35.592362 [debug] [MainThread]: Command `dbt run` failed at 23:11:35.592362 after 0.08 seconds
[0m23:11:35.593329 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027651DF1090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027659099310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027659099410>]}
[0m23:11:35.593329 [debug] [MainThread]: Flushing usage events
[0m13:00:22.017583 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BCA5881710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BCA4BA21D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BCA53A91D0>]}


============================== 13:00:22.024165 | 4454557c-3502-417c-9481-909350d51960 ==============================
[0m13:00:22.024165 [info ] [MainThread]: Running with dbt=1.7.3
[0m13:00:22.024670 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:00:22.026676 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\OneDrive\Documentos\triade\dbt_study_case\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:00:22.027678 [debug] [MainThread]: Command `dbt run` failed at 13:00:22.027678 after 0.09 seconds
[0m13:00:22.028676 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC9E0C1090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BCA586AED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BCA586ACD0>]}
[0m13:00:22.029677 [debug] [MainThread]: Flushing usage events
[0m23:17:25.565286 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002175A3C7290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002175A3C7910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002175A0F6E90>]}


============================== 23:17:25.570791 | 8725bd94-5d6e-4e1f-83f2-ac7fe050656f ==============================
[0m23:17:25.570791 [info ] [MainThread]: Running with dbt=1.7.3
[0m23:17:25.571798 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:17:25.572800 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\OneDrive\Documentos\triade\dbt_study_case\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:17:25.574798 [debug] [MainThread]: Command `dbt test` failed at 23:17:25.574798 after 0.08 seconds
[0m23:17:25.575802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021753191090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002175A90F590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002175A90F010>]}
[0m23:17:25.576801 [debug] [MainThread]: Flushing usage events
[0m14:09:27.646815 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F780AC990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F7BBF4450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F7B7BCF50>]}


============================== 14:09:27.650461 | a62a25a7-3283-4930-9aaf-1bfcf403dc8d ==============================
[0m14:09:27.650461 [info ] [MainThread]: Running with dbt=1.7.3
[0m14:09:27.651504 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test -s dm__fact_grades_students', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:09:27.652469 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\OneDrive\Documentos\triade\dbt_study_case\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:09:27.653467 [debug] [MainThread]: Command `dbt test` failed at 14:09:27.653467 after 0.06 seconds
[0m14:09:27.654505 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F7BBF6790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F74430FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F7B7DD5D0>]}
[0m14:09:27.655470 [debug] [MainThread]: Flushing usage events
[0m13:35:50.431137 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F82E7162D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F82E490350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F82E714490>]}


============================== 13:35:50.439831 | ff6be23d-40b0-44da-83b3-521bd3721155 ==============================
[0m13:35:50.439831 [info ] [MainThread]: Running with dbt=1.7.3
[0m13:35:50.440800 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\marco\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run -s stg__dim_course_details', 'send_anonymous_usage_stats': 'True'}
[0m13:35:50.441794 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\marco\OneDrive\Documentos\triade\dbt_study_case\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:35:50.444138 [debug] [MainThread]: Command `dbt run` failed at 13:35:50.442829 after 0.13 seconds
[0m13:35:50.445146 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F82E703710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F827410F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F82E7DE510>]}
[0m13:35:50.445700 [debug] [MainThread]: Flushing usage events
